version: "3.9"

services:
  db:
    image: postgres:18-alpine
    container_name: booktracker-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booksdb
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis:
    image: redis:7-alpine
    container_name: booktracker-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

  publisher:
    build: ./publisher
    container_name: booktracker-publisher
    environment:
      REDIS_URL: redis://redis:6379/0
      EVENT_ID_POOL_SIZE: 8
      PUBLISH_INTERVAL_MS: 1000
    depends_on:
      - redis

  backend:
    build: ./backend
    container_name: booktracker-backend
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload --log-level error
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/booksdb
      REDIS_URL: redis://redis:6379/0
      CACHE_TTL_SECONDS: 30
      WATCHFILES_FORCE_POLLING: true
      LOG_LEVEL: ERROR
    ports:
      - "8000:8000"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65535
      # Increases the queue for 'pending' connections (Listen Backlog)
      - net.core.somaxconn=10000 
      # Optional: Increases the memory allocated for TCP sockets
      # - net.ipv4.tcp_mem=786432 1048576 1572864
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  frontend:
    build: ./frontend
    container_name: booktracker-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    environment:
      CHOKIDAR_USEPOLLING: true
    depends_on:
      - backend

  # k6:
  #   image: grafana/k6:latest
  #   container_name: booktracker-k6
  #   volumes:
  #     - ./load-testing:/scripts
  #   command: run /scripts/load-test.js
  #   environment:
  #     BASE_URL: http://backend:8000
  #   depends_on:
  #     backend:
  #       condition: service_healthy

  k6-ws:
    image: grafana/k6:latest
    container_name: booktracker-k6-ws
    volumes:
      - ./load-testing:/scripts
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    sysctls:
      # Expands the range of local ports k6 can use to talk to the API
      - net.ipv4.ip_local_port_range=1024 65535
      # Allows k6 to quickly reuse ports in TIME_WAIT state
      - net.ipv4.tcp_tw_reuse=1
    command: run /scripts/load-test-ws.js
    environment:
      BASE_URL: http://backend:8000
    depends_on:
      backend:
        condition: service_healthy

